development:
  adapter: postgresql
  encoding: unicode
  database: brettallenmusic_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: brettallenmusic_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: ec2-54-204-37-113.compute-1.amazonaws.com
  port: 5432